[Hotkey]
# 触发输入法（默认 Ctrl+Space）
TriggerKeys=Control+space,ZenKaku_Hankaku
# 启用输入法
EnumerateForwardKeys=Control+Shift_R
EnumerateBackwardKeys=Control+Shift_L

[Hotkey/PrevPage]
0=Up

[Hotkey/NextPage]
0=Down

[Behavior]
# 关键：默认激活输入法（开机即中文，不用每次按 Ctrl+Space）
ActiveByDefault=True
# 默认共享输入法状态（所有窗口统一中/英文）
ShareInputState=All
