#!/bin/bash
# ======================================================================
# install-tdengine-client.sh — 用 Docker 镜像提供 TDengine 客户端（taos CLI）
#
# 思路：
#   不在宿主机 dpkg 安装 deb（官方下载中心无稳定直链），而是拉官方 Docker
#   镜像 tdengine/tdengine:<版本>，容器里自带 taos / taosdump / taosBenchmark。
#   再生成一个宿主机 wrapper ~/bin/taos，敲 taos 即进容器、连远端。
#
# 关键坑（实测）：
#   1) 官方镜像 entrypoint 是起 taosd 服务端的，直接 docker run ... taos 会被
#      服务端初始化流程劫持 → 必须 --entrypoint 覆盖
#   2) 镜像构建时 /etc/taos/taos.cfg 的 fqdn 写死成 buildkitsandbox，客户端
#      启动会做 FQDN 自检反解，失败 → failed to init cfg ... Unable to resolve FQDN
#      解法：启动时 sed 把 fqdn 改成 localhost
#   3) 连远端用 --network host 直通本机网络（db-server.example.com 在 /etc/hosts）
#
# 功能：
#   1) docker pull tdengine/tdengine:<版本>（默认 3.3.4.3，须与服务端对齐）
#   2) 生成 ~/bin/taos、~/bin/taosdump wrapper（进容器跑，自动修 fqdn）
#   3) 校验：taos --version / 连远端 select server_version()
#   4) 卸载：删 wrapper + 镜像（可选）
#
# 适用：Ubuntu 24.04 + Docker，本地连内网服务器 TDengine（服务端不在本地）
# 对应文档：docs/20-工具-TDengine客户端.md
# ======================================================================

set -u

# ---------- 颜色与基础工具（风格与项目其它 install-*.sh 一致） ----------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }
title() { echo; echo -e "${CYAN}==== $* ====${NC}"; }

need_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        err "未找到 docker 命令。请先安装 Docker（见 docs/13-开发-Docker部署迁移.md）"
        exit 1
    fi
    if ! docker info >/dev/null 2>&1; then
        err "docker daemon 不可用，请先启动：sudo systemctl start docker"
        exit 1
    fi
}

# 真实用户家目录（脚本可能被 sudo 调用）
REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
BIN_DIR="${REAL_HOME}/bin"

# ---------- 版本 ----------
# 必须与远端服务端对齐（3.x 协议不跨大版本兼容），内网服务器 是 tdengine:3.3.4.3
TDENGINE_VERSION="${TDENGINE_VERSION:-3.3.4.3}"
IMAGE="tdengine/tdengine:${TDENGINE_VERSION}"

# wrapper 模板：进容器 → 修 fqdn → 跑客户端命令
# 用法与原生 taos 完全一致：taos -h xxx -u root -p ...
WRAPPER_TEMPLATE='#!/bin/bash
# Auto-generated by install-tdengine-client.sh — TDengine 客户端 Docker wrapper
# 敲 taos 即进 tdengine/tdengine:{VER} 容器跑客户端，自动修 fqdn 绕过 FQDN 自检
# 用法与原生 taos 一致：taos -h db-server.example.com -u root -p
set -u
IMAGE="tdengine/tdengine:{VER}"
# 若未显式传 -h，默认连内网服务器
if [[ " $* " != *" -h "* ]] && [[ " $* " != *" --host "* ]]; then
    set -- -h db-server.example.com "$@"
fi
exec docker run --rm -i --network host \
    --entrypoint bash "$IMAGE" \
    -c "sed -i '\''s/^fqdn .*/fqdn localhost/'\'' /etc/taos/taos.cfg >/dev/null 2>&1; exec /usr/bin/{CMD} \"\$@\"" _ "$@"
'

# ---------- 步骤 1：拉镜像 ----------
do_pull() {
    need_docker
    title "步骤 1 · 拉取 $IMAGE"
    if docker image inspect "$IMAGE" >/dev/null 2>&1; then
        ok "镜像已存在：$IMAGE（跳过拉取，如需更新先 docker rmi）"
        return 0
    fi
    info "docker pull $IMAGE（约 200M，请稍候）..."
    docker pull "$IMAGE" || { err "拉取失败，请检查网络或镜像 tag"; exit 1; }
    ok "已拉取 $IMAGE"
}

# ---------- 步骤 2：写 wrapper ----------
write_wrapper() {
    title "步骤 2 · 生成 wrapper 到 $BIN_DIR"
    mkdir -p "$BIN_DIR"

    # 检查 ~/bin 是否在 PATH（看实际 PATH 环境变量，而非 grep bashrc）
    case ":${PATH:-}:" in
        *":${BIN_DIR}:"*) ok "$BIN_DIR 已在 PATH" ;;
        *)
            warn "$BIN_DIR 不在 PATH，新开终端可能敲不到 taos"
            info "可手动加：echo 'export PATH=\$HOME/bin:\$PATH' >> ~/.bashrc"
            ;;
    esac

    # 生成 taos、taosdump、taosBenchmark 三个 wrapper
    local cmd
    for cmd in taos taosdump taosBenchmark; do
        local wrapper="${BIN_DIR}/${cmd}"
        # taosBenchmark 的命令名在容器里是 taosBenchmark，wrapper 同名
        echo "$WRAPPER_TEMPLATE" | sed -e "s/{VER}/${TDENGINE_VERSION}/g" -e "s/{CMD}/${cmd}/g" > "$wrapper"
        chmod +x "$wrapper"
        chown "$REAL_USER":"$(id -g "$REAL_USER")" "$wrapper" 2>/dev/null || true
        ok "wrapper：$wrapper"
    done
}

# ---------- 步骤 3：校验 ----------
do_verify() {
    title "步骤 3 · 校验"

    # 1) 镜像
    if docker image inspect "$IMAGE" >/dev/null 2>&1; then
        ok "镜像就位：$IMAGE"
    else
        err "镜像未拉取：$IMAGE，请先执行 pull"
        exit 1
    fi

    # 2) wrapper
    local w="${BIN_DIR}/taos"
    if [ -x "$w" ]; then
        ok "wrapper 就位：$w"
    else
        err "wrapper 缺失：$w，请先执行 install"
        exit 1
    fi

    # 3) 版本（直接用容器跑，不依赖 wrapper PATH 是否生效）
    info "容器内 taos --version："
    docker run --rm --entrypoint /usr/bin/taos "$IMAGE" --version 2>&1 | head -3

    # 4) 连远端（用 wrapper，验证整条链路）
    if timeout 20 "$w" -h db-server.example.com -P 6030 -u root -ptaosdata -s "select server_version();" 2>&1 | grep -q "3.3.4.3"; then
        ok "连内网服务器 成功，读到 server_version = ${TDENGINE_VERSION}"
    else
        warn "连远端验证未通过（远端服务端未就绪/账号密码已改/网络问题），不影响本地安装"
        info "  可稍后手动测试：~/bin/taos -h db-server.example.com -u root -p"
    fi
}

# ---------- 交互式连接 ----------
do_connect() {
    local w="${BIN_DIR}/taos"
    [ -x "$w" ] || { err "wrapper 未安装，请先：sudo bash $0 install"; exit 1; }

    title "交互式连接远端 TDengine"
    local host port user
    read -rp "远端主机 [db-server.example.com]: " host
    host="${host:-db-server.example.com}"
    read -rp "端口 [6030]: " port
    port="${port:-6030}"
    read -rp "用户名 [root]: " user
    user="${user:-root}"

    info "进入容器连 $host:$port（默认密码 taosdata，回车后输入）..."
    echo
    "$w" -h "$host" -P "$port" -u "$user" -p
}

# ---------- 卸载 ----------
do_remove() {
    title "卸载 TDengine 客户端 wrapper"
    rm -fv "${BIN_DIR}/taos" "${BIN_DIR}/taosdump" "${BIN_DIR}/taosBenchmark" 2>/dev/null || true
    ok "已删除 wrapper"

    read -rp "是否一并删除 Docker 镜像 $IMAGE？[y/N] " ans
    if [[ "${ans:-N}" =~ ^[Yy]$ ]]; then
        docker rmi "$IMAGE" 2>/dev/null && ok "已删除镜像 $IMAGE" || warn "镜像删除失败（可能正被使用）"
    else
        info "保留镜像 $IMAGE（其它容器可能依赖）"
    fi
    ok "卸载完成"
}

# ---------- 升级（换版本） ----------
do_upgrade() {
    title "切换 TDengine 客户端版本"
    info "当前：$TDENGINE_VERSION"
    info "注意：版本必须与远端服务端对齐，否则协议不兼容"
    local newver
    read -rp "新版本号（留空取消）: " newver
    [ -z "$newver" ] && { info "已取消"; return 0; }
    TDENGINE_VERSION="$newver"
    IMAGE="tdengine/tdengine:${newver}"
    do_pull
    write_wrapper
    ok "已切换到 $newver，重生成 wrapper"
    info "原镜像未自动删除，如需清理：docker rmi tdengine/tdengine:<旧版本>"
}

# ---------- 帮助 ----------
show_help() {
    cat << EOF
用法：bash $0 [子命令]

子命令（缺省 = all，执行 pull → 写 wrapper → verify）：
  pull     拉取 tdengine/tdengine:<版本> Docker 镜像（需 docker 权限）
  install  生成 ~/bin/taos、~/bin/taosdump 等 wrapper
  verify   校验镜像 + wrapper + 连远端
  connect  交互式连远端 TDengine
  upgrade  切换客户端版本（重新拉镜像 + 重生成 wrapper）
  remove   删 wrapper（可选删镜像）
  all      pull → 写 wrapper → verify（推荐）
  help     显示本帮助

环境变量：
  TDENGINE_VERSION  客户端版本号，默认 3.3.4.3（须与远端服务端对齐）

示例：
  bash $0                    # 一键安装（拉镜像 + wrapper + 校验）
  bash $0 pull               # 仅拉镜像
  bash $0 connect            # 连内网服务器
  TDENGINE_VERSION=3.3.5.0 bash $0 all   # 装其它版本

装完后的日常用法（与原生 taos 完全一致）：
  taos -h db-server.example.com -u root -p                       # 进交互式 shell
  taos -h db-server.example.com -u root -p -s 'show databases;'  # 执行一条 SQL
  taos -h db-server.example.com -u root -p                       # 不带 -h 也行，wrapper 默认 内网服务器
  taosdump -h db-server.example.com -u root -p -o /tmp/dump db   # 导出
EOF
}

# ---------- 入口 ----------
main() {
    local cmd="${1:-all}"
    case "$cmd" in
        pull)         do_pull ;;
        install|wrap) do_pull; write_wrapper ;;
        verify)       do_verify ;;
        connect)      do_connect ;;
        upgrade)      do_upgrade ;;
        remove)       do_remove ;;
        all)          do_pull; write_wrapper; do_verify ;;
        help|-h|--help) show_help ;;
        *) err "未知子命令：$cmd"; show_help; exit 1 ;;
    esac
}

main "$@"
